const ROUTE_LABEL_KEYS = {
  '/': 'nav.home',
  '/anniversaries': 'nav.anniversaries',
  '/author': 'nav.author',
  '/backup': 'nav.backup',
  '/quiz': 'nav.quiz',
  '/bookmarks': 'nav.bookmarks',
  '/books': 'nav.books',
  '/change-log': 'nav.changeLog',
  '/charts': 'nav.charts',
  '/distinctive-persons': 'nav.distinctivePersons',
  '/dna': 'nav.dna',
  '/families': 'nav.families',
  '/duplicates': 'nav.duplicates',
  '/events': 'nav.events',
  '/family-events': 'nav.familyEvents',
  '/export': 'nav.export',
  '/facts': 'nav.facts',
  '/familysearch': 'nav.familySearch',
  '/favorites': 'nav.favorites',
  '/globe': 'nav.globe',
  '/groups': 'nav.personGroups',
  '/heritage-tree': 'nav.heritageTree',
  '/labels': 'nav.labels',
  '/lineages': 'nav.lineages',
  '/lds-ordinances': 'nav.ldsOrdinances',
  '/lists': 'nav.lists',
  '/maintenance': 'nav.maintenance',
  '/map': 'nav.map',
  '/maps-diagram': 'nav.mapsDiagram',
  '/marriages': 'nav.marriages',
  '/media': 'nav.media',
  '/person-analysis': 'nav.personAnalysis',
  '/persons': 'nav.persons',
  '/places': 'nav.places',
  '/plausibility': 'nav.plausibility',
  '/plausibility-list': 'nav.plausibilityList',
  '/publish': 'nav.publish',
  '/repositories': 'nav.repositories',
  '/reports': 'nav.reports',
  '/research': 'nav.research',
  '/saved-charts': 'nav.savedCharts',
  '/search': 'nav.search',
  '/settings': 'nav.settings',
  '/actions': 'nav.actions',
  '/subtree': 'nav.subtree',
  '/slideshow': 'nav.slideshow',
  '/sources': 'nav.sources',
  '/search-and-replace': 'nav.searchAndReplace',
  '/statistics': 'nav.statistics',
  '/stories': 'nav.stories',
  '/templates': 'nav.templates',
  '/todos': 'nav.todos',
  '/tree': 'nav.tree',
  '/tribal-affiliations': 'nav.tribalAffiliations',
  '/views': 'nav.views',
  '/views/family-quiz': 'nav.familyQuiz',
  '/views/media-gallery': 'nav.media',
  '/views/statistic-maps': 'nav.mapsDiagram',
  '/views/virtual-globe': 'nav.globe',
  '/views/virtual-map': 'nav.map',
  '/family-search': 'nav.familySearch',
  '/web-search': 'nav.webSearch',
  '/websites': 'nav.websites',
  '/world-history': 'nav.worldHistory',
  // Secondary paths that render the same page as a labelled route, plus the
  // settings panels. Without a key here the page name falls back to the raw
  // path segment — which the mobile title bar now shows to the reader.
  '/statistic-maps': 'nav.mapsDiagram',
  '/virtual-map': 'nav.map',
  '/virtual-globe': 'nav.globe',
  '/media-gallery': 'nav.media',
  '/family-quiz': 'nav.familyQuiz',
  '/marriage-list': 'nav.marriages',
  '/facts-list': 'nav.facts',
  '/anniversary-list': 'nav.anniversaries',
  '/author-information': 'nav.author',
  '/chart-split': 'nav.chartSplit',
  '/reference-numbering': 'nav.referenceNumbering',
  '/custom-validation': 'nav.customValidation',
  '/smart-filters': 'nav.smartFilters',
  '/custom-types': 'nav.customTypes',
  '/arabic-islamic': 'nav.arabicIslamic',
  '/tree-layout': 'nav.treeLayout',
  '/content-download': 'nav.contentDownload',
  '/edit-controllers': 'nav.editControllers',
};

const CATEGORY_KEYS = {
  Charts: 'categories.charts',
  Edit: 'categories.edit',
  Favorites: 'categories.favorites',
  Tools: 'categories.tools',
  Lists: 'categories.lists',
  Publish: 'categories.publish',
  Reports: 'categories.reports',
  Views: 'categories.views',
};

export function routeLabelKey(route) {
  return ROUTE_LABEL_KEYS[route] || null;
}

export function categoryLabelKey(category) {
  return CATEGORY_KEYS[category] || null;
}
