/**
 * Compact built-in world-history dataset for the timeline widget.
 * Each entry: { year, end?, title, region, kind }.
 */
export const WORLD_EVENTS = [
  { year: 1492, title: 'Columbus arrives in the Americas', region: 'Atlantic', kind: 'Exploration' },
  { year: 1517, title: 'Protestant Reformation begins', region: 'Europe', kind: 'Religion' },
  { year: 1607, title: 'Jamestown colony founded', region: 'North America', kind: 'Settlement' },
  { year: 1620, title: 'Mayflower lands at Plymouth', region: 'North America', kind: 'Settlement' },
  { year: 1648, title: 'Peace of Westphalia', region: 'Europe', kind: 'Treaty' },
  { year: 1689, end: 1697, title: 'Nine Years\' War', region: 'Europe', kind: 'War' },
  { year: 1707, title: 'Acts of Union — Great Britain', region: 'Europe', kind: 'Politics' },
  { year: 1756, end: 1763, title: 'Seven Years\' War', region: 'Global', kind: 'War' },
  { year: 1775, end: 1783, title: 'American Revolutionary War', region: 'North America', kind: 'War' },
  { year: 1789, title: 'French Revolution begins', region: 'Europe', kind: 'Politics' },
  { year: 1803, title: 'Louisiana Purchase', region: 'North America', kind: 'Politics' },
  { year: 1804, end: 1815, title: 'Napoleonic Wars', region: 'Europe', kind: 'War' },
  { year: 1815, title: 'Battle of Waterloo', region: 'Europe', kind: 'War' },
  { year: 1820, title: 'First wave of European emigration to Americas', region: 'Atlantic', kind: 'Migration' },
  { year: 1845, end: 1852, title: 'Great Famine in Ireland', region: 'Europe', kind: 'Disaster' },
  { year: 1848, title: 'European Revolutions', region: 'Europe', kind: 'Politics' },
  { year: 1861, end: 1865, title: 'American Civil War', region: 'North America', kind: 'War' },
  { year: 1869, title: 'Suez Canal opens', region: 'Africa / Asia', kind: 'Infrastructure' },
  { year: 1870, end: 1871, title: 'Franco-Prussian War', region: 'Europe', kind: 'War' },
  { year: 1881, end: 1914, title: 'Great wave of European emigration to USA', region: 'Atlantic', kind: 'Migration' },
  { year: 1898, title: 'Spanish-American War', region: 'Atlantic / Pacific', kind: 'War' },
  { year: 1914, end: 1918, title: 'World War I', region: 'Global', kind: 'War' },
  { year: 1917, title: 'Russian Revolution', region: 'Europe', kind: 'Politics' },
  { year: 1918, end: 1920, title: '1918 influenza pandemic', region: 'Global', kind: 'Disease' },
  { year: 1929, title: 'Wall Street Crash', region: 'North America', kind: 'Economy' },
  { year: 1936, end: 1939, title: 'Spanish Civil War', region: 'Europe', kind: 'War' },
  { year: 1939, end: 1945, title: 'World War II', region: 'Global', kind: 'War' },
  { year: 1947, title: 'Partition of India', region: 'South Asia', kind: 'Politics' },
  { year: 1948, title: 'State of Israel founded', region: 'Middle East', kind: 'Politics' },
  { year: 1948, end: 1953, title: 'Korean War', region: 'East Asia', kind: 'War' },
  { year: 1955, end: 1975, title: 'Vietnam War', region: 'Southeast Asia', kind: 'War' },
  { year: 1957, title: 'Sputnik launches', region: 'Global', kind: 'Science' },
  { year: 1969, title: 'Apollo 11 Moon landing', region: 'Global', kind: 'Science' },
  { year: 1973, title: 'Oil crisis', region: 'Global', kind: 'Economy' },
  { year: 1979, title: 'Iranian Revolution', region: 'Middle East', kind: 'Politics' },
  { year: 1980, end: 1988, title: 'Iran–Iraq War', region: 'Middle East', kind: 'War' },
  { year: 1989, title: 'Fall of the Berlin Wall', region: 'Europe', kind: 'Politics' },
  { year: 1990, end: 1991, title: 'Gulf War', region: 'Middle East', kind: 'War' },
  { year: 1991, title: 'Soviet Union dissolves', region: 'Europe / Asia', kind: 'Politics' },
  { year: 2001, title: 'September 11 attacks', region: 'North America', kind: 'Politics' },
  { year: 2003, end: 2011, title: 'Iraq War', region: 'Middle East', kind: 'War' },
  { year: 2008, title: 'Global financial crisis', region: 'Global', kind: 'Economy' },
  { year: 2010, end: 2012, title: 'Arab Spring', region: 'North Africa / Middle East', kind: 'Politics' },
  { year: 2020, end: 2023, title: 'COVID-19 pandemic', region: 'Global', kind: 'Disease' },
];
