export const panelStyles = {
  panel: {
    position: 'absolute',
    top: 12,
    insetInlineEnd: 12,
    bottom: 12,
    width: 320,
    zIndex: 26,
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 10,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card) / 0.97)',
    boxShadow: '0 18px 48px rgb(0 0 0 / 0.18)',
    backdropFilter: 'blur(18px)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderBottom: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary) / 0.6)',
  },
  title: {
    font: '800 13px -apple-system, system-ui, sans-serif',
    color: 'hsl(var(--foreground))',
  },
  closeButton: {
    height: 26,
    width: 26,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card))',
    cursor: 'pointer',
    font: '600 16px -apple-system, system-ui, sans-serif',
    color: 'hsl(var(--muted-foreground))',
    lineHeight: '20px',
  },
  scroll: {
    flex: 1,
    overflowY: 'auto',
    padding: 8,
  },
  section: {
    borderBottom: '1px solid hsl(var(--border) / 0.5)',
    paddingBottom: 4,
    marginBottom: 4,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    border: 0,
    background: 'transparent',
    padding: '8px 6px',
    cursor: 'pointer',
    font: '700 12px -apple-system, system-ui, sans-serif',
    color: 'hsl(var(--foreground))',
    textAlign: 'start',
  },
  disclosure: {
    display: 'inline-block',
    width: 12,
    color: 'hsl(var(--muted-foreground))',
    font: '700 10px -apple-system, system-ui, sans-serif',
  },
  sectionBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: '4px 6px 8px',
  },
  row: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  rowLabel: {
    font: '600 11px -apple-system, system-ui, sans-serif',
    color: 'hsl(var(--foreground))',
  },
  select: {
    width: '100%',
    height: 28,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card))',
    color: 'hsl(var(--foreground))',
    font: '600 11px -apple-system, system-ui, sans-serif',
    padding: '0 6px',
  },
  sliderHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sliderValue: {
    font: '600 10px ui-monospace, SFMono-Regular, Menlo, monospace',
    color: 'hsl(var(--muted-foreground))',
  },
  slider: {
    width: '100%',
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    cursor: 'pointer',
  },
  checkbox: {
    margin: 0,
  },
};
