export const styles = {
  shell: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    background: 'hsl(var(--background))',
  },
  canvas: {
    width: '100%',
    height: '100%',
  },
  controls: {
    position: 'absolute',
    top: 12,
    insetInlineEnd: 12,
    display: 'flex',
    gap: 6,
    padding: 6,
    borderRadius: 8,
    background: 'hsl(var(--card) / 0.82)',
    border: '1px solid hsl(var(--border))',
    boxShadow: '0 10px 24px rgb(0 0 0 / 0.12)',
    backdropFilter: 'blur(12px)',
    transition: 'opacity 160ms ease, transform 160ms ease',
  },
  controlsHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(-5px)',
  },
  bottomDock: {
    position: 'absolute',
    left: '50%',
    bottom: 14,
    transform: 'translateX(-50%)',
    maxWidth: 'calc(100% - 32px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 12,
    padding: '8px 10px',
    borderRadius: 8,
    background: 'hsl(var(--card) / 0.86)',
    border: '1px solid hsl(var(--border))',
    boxShadow: '0 14px 34px rgb(0 0 0 / 0.16)',
    backdropFilter: 'blur(14px)',
    color: 'hsl(var(--foreground))',
    overflow: 'auto',
    transition: 'opacity 160ms ease, transform 160ms ease',
  },
  bottomDockHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateX(-50%) translateY(8px)',
  },
  dockGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  navDockGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
    paddingInlineStart: 2,
  },
  dockLabel: {
    color: 'hsl(var(--muted-foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    whiteSpace: 'nowrap',
  },
  zoomSlider: {
    width: 118,
    accentColor: 'hsl(var(--primary))',
  },
  zoomReadout: {
    width: 42,
    color: 'hsl(var(--foreground))',
    font: '750 11px -apple-system, system-ui, sans-serif',
  },
  metric: {
    minWidth: 58,
    textAlign: 'center',
    padding: '2px 6px',
    borderInlineStart: '1px solid hsl(var(--border))',
  },
  metricValue: {
    display: 'block',
    color: 'hsl(var(--foreground))',
    font: '800 13px -apple-system, system-ui, sans-serif',
  },
  metricLabel: {
    display: 'block',
    color: 'hsl(var(--muted-foreground))',
    font: '650 10px -apple-system, system-ui, sans-serif',
  },
  dockButton: {
    height: 30,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '750 11px -apple-system, system-ui, sans-serif',
    padding: '0 10px',
    cursor: 'pointer',
  },
  selectLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    color: 'hsl(var(--muted-foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    whiteSpace: 'nowrap',
  },
  selectText: {
    display: 'inline-block',
  },
  select: {
    height: 30,
    minWidth: 84,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    padding: '0 24px 0 8px',
    cursor: 'pointer',
  },
  navigationSelect: {
    height: 30,
    minWidth: 150,
    maxWidth: 230,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    padding: '0 24px 0 8px',
    cursor: 'pointer',
  },
  iconButton: {
    width: 31,
    height: 31,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 15px -apple-system, system-ui, sans-serif',
    cursor: 'pointer',
  },
  fitButton: {
    height: 31,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 12px -apple-system, system-ui, sans-serif',
    padding: '0 10px',
    cursor: 'pointer',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'hsl(var(--muted-foreground))',
    font: '14px -apple-system, system-ui, sans-serif',
    pointerEvents: 'none',
    background: 'hsl(var(--background) / 0.45)',
  },
  hoverCard: {
    position: 'fixed',
    zIndex: 40,
    maxWidth: 220,
    borderRadius: 8,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card) / 0.92)',
    boxShadow: '0 14px 30px rgb(0 0 0 / 0.18)',
    backdropFilter: 'blur(14px)',
    padding: '8px 10px',
    pointerEvents: 'none',
  },
  hoverName: {
    color: 'hsl(var(--foreground))',
    font: '750 12px -apple-system, system-ui, sans-serif',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  hoverMeta: {
    color: 'hsl(var(--muted-foreground))',
    font: '650 11px -apple-system, system-ui, sans-serif',
    marginTop: 2,
  },
  contextMenu: {
    position: 'fixed',
    zIndex: 50,
    width: 190,
    borderRadius: 8,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card) / 0.96)',
    boxShadow: '0 18px 40px rgb(0 0 0 / 0.22)',
    backdropFilter: 'blur(14px)',
    padding: 6,
    color: 'hsl(var(--foreground))',
  },
  contextHeader: {
    padding: '7px 8px 8px',
    borderBottom: '1px solid hsl(var(--border))',
    marginBottom: 4,
  },
  contextName: {
    font: '760 12px -apple-system, system-ui, sans-serif',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  contextMeta: {
    color: 'hsl(var(--muted-foreground))',
    font: '650 11px -apple-system, system-ui, sans-serif',
    marginTop: 2,
  },
  contextItem: {
    width: '100%',
    minHeight: 30,
    border: 0,
    borderRadius: 6,
    background: 'transparent',
    color: 'hsl(var(--foreground))',
    textAlign: 'start',
    font: '700 12px -apple-system, system-ui, sans-serif',
    padding: '0 8px',
    cursor: 'pointer',
  },
};

export function dockToggleStyle(active) {
  return {
    ...styles.dockButton,
    background: active ? 'hsl(var(--primary) / 0.14)' : 'hsl(var(--secondary))',
    borderColor: active ? 'hsl(var(--primary) / 0.45)' : 'hsl(var(--border))',
    color: active ? 'hsl(var(--foreground))' : 'hsl(var(--muted-foreground))',
  };
}
