export const styles = {
  shell: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    background: 'hsl(var(--background))',
  },
  canvas: {
    width: '100%',
    height: '100%',
  },
  macTopBar: {
    position: 'absolute',
    top: 12,
    left: 12,
    zIndex: 22,
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    padding: 6,
    borderRadius: 8,
    background: 'hsl(var(--card) / 0.88)',
    border: '1px solid hsl(var(--border))',
    boxShadow: '0 10px 24px rgb(0 0 0 / 0.12)',
    backdropFilter: 'blur(14px)',
    maxWidth: 'calc(100% - 104px)',
    overflowX: 'auto',
  },
  macBarButton: {
    height: 31,
    flexShrink: 0,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '750 12px -apple-system, system-ui, sans-serif',
    padding: '0 10px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  // Mobile touch-target bump (merge over the base buttons on small screens).
  macBarButtonMobile: {
    height: 40,
    minHeight: 40,
    padding: '0 14px',
  },
  macActionWrap: {
    position: 'relative',
    flexShrink: 0,
  },
  macActionMenu: {
    position: 'absolute',
    top: 38,
    left: 0,
    zIndex: 30,
    width: 186,
    borderRadius: 8,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card) / 0.98)',
    boxShadow: '0 18px 40px rgb(0 0 0 / 0.22)',
    backdropFilter: 'blur(14px)',
    padding: 6,
  },
  macActionItem: {
    width: '100%',
    minHeight: 30,
    border: 0,
    borderRadius: 6,
    background: 'transparent',
    color: 'hsl(var(--foreground))',
    textAlign: 'start',
    font: '700 12px -apple-system, system-ui, sans-serif',
    padding: '0 8px',
    cursor: 'pointer',
  },
  controls: {
    position: 'absolute',
    top: 12,
    insetInlineEnd: 12,
    display: 'flex',
    gap: 6,
    padding: 6,
    borderRadius: 8,
    background: 'hsl(var(--card) / 0.82)',
    border: '1px solid hsl(var(--border))',
    boxShadow: '0 10px 24px rgb(0 0 0 / 0.12)',
    backdropFilter: 'blur(12px)',
    transition: 'opacity 160ms ease, transform 160ms ease',
  },
  controlsHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(-5px)',
  },
  bottomDock: {
    position: 'absolute',
    left: '50%',
    bottom: 14,
    transform: 'translateX(-50%)',
    maxWidth: 'calc(100% - 32px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 12,
    padding: '8px 10px',
    borderRadius: 8,
    background: 'hsl(var(--card) / 0.86)',
    border: '1px solid hsl(var(--border))',
    boxShadow: '0 14px 34px rgb(0 0 0 / 0.16)',
    backdropFilter: 'blur(14px)',
    color: 'hsl(var(--foreground))',
    overflow: 'auto',
    transition: 'opacity 160ms ease, transform 160ms ease',
  },
  bottomDockHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateX(-50%) translateY(8px)',
  },
  // Mobile: tighten the dock so it covers less of the canvas; cap its height and
  // let the contents scroll instead of wrapping into many tall rows.
  bottomDockMobile: {
    left: 8,
    right: 8,
    transform: 'none',
    maxWidth: 'none',
    flexWrap: 'nowrap',
    justifyContent: 'flex-start',
    gap: 8,
    padding: '6px 8px',
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  bottomDockHiddenMobile: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(8px)',
  },
  dockGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  navDockGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
    paddingInlineStart: 2,
  },
  dockLabel: {
    color: 'hsl(var(--muted-foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    whiteSpace: 'nowrap',
  },
  zoomSlider: {
    width: 118,
    accentColor: 'hsl(var(--primary))',
  },
  zoomReadout: {
    width: 42,
    color: 'hsl(var(--foreground))',
    font: '750 11px -apple-system, system-ui, sans-serif',
  },
  metric: {
    minWidth: 58,
    textAlign: 'center',
    padding: '2px 6px',
    borderInlineStart: '1px solid hsl(var(--border))',
  },
  metricValue: {
    display: 'block',
    color: 'hsl(var(--foreground))',
    font: '800 13px -apple-system, system-ui, sans-serif',
  },
  metricLabel: {
    display: 'block',
    color: 'hsl(var(--muted-foreground))',
    font: '650 10px -apple-system, system-ui, sans-serif',
  },
  dockButton: {
    height: 30,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '750 11px -apple-system, system-ui, sans-serif',
    padding: '0 10px',
    cursor: 'pointer',
  },
  // Mobile touch-target bump for dock buttons (merge over dockButton).
  dockButtonMobile: {
    height: 38,
    minHeight: 38,
    flexShrink: 0,
    padding: '0 12px',
  },
  selectLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    color: 'hsl(var(--muted-foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    whiteSpace: 'nowrap',
  },
  selectText: {
    display: 'inline-block',
  },
  select: {
    height: 30,
    minWidth: 84,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    padding: '0 24px 0 8px',
    cursor: 'pointer',
  },
  navigationSelect: {
    height: 30,
    minWidth: 150,
    maxWidth: 230,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 11px -apple-system, system-ui, sans-serif',
    padding: '0 24px 0 8px',
    cursor: 'pointer',
  },
  iconButton: {
    width: 31,
    height: 31,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 15px -apple-system, system-ui, sans-serif',
    cursor: 'pointer',
  },
  fitButton: {
    height: 31,
    borderRadius: 6,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--secondary))',
    color: 'hsl(var(--foreground))',
    font: '700 12px -apple-system, system-ui, sans-serif',
    padding: '0 10px',
    cursor: 'pointer',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'hsl(var(--muted-foreground))',
    font: '14px -apple-system, system-ui, sans-serif',
    pointerEvents: 'none',
    background: 'hsl(var(--background) / 0.45)',
  },
  hoverCard: {
    position: 'fixed',
    zIndex: 40,
    maxWidth: 220,
    borderRadius: 8,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card) / 0.92)',
    boxShadow: '0 14px 30px rgb(0 0 0 / 0.18)',
    backdropFilter: 'blur(14px)',
    padding: '8px 10px',
    pointerEvents: 'none',
  },
  hoverName: {
    color: 'hsl(var(--foreground))',
    font: '750 12px -apple-system, system-ui, sans-serif',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  hoverMeta: {
    color: 'hsl(var(--muted-foreground))',
    font: '650 11px -apple-system, system-ui, sans-serif',
    marginTop: 2,
  },
  contextMenu: {
    position: 'fixed',
    zIndex: 50,
    width: 230,
    borderRadius: 8,
    border: '1px solid hsl(var(--border))',
    background: 'hsl(var(--card) / 0.96)',
    boxShadow: '0 18px 40px rgb(0 0 0 / 0.22)',
    backdropFilter: 'blur(14px)',
    padding: 6,
    color: 'hsl(var(--foreground))',
  },
  contextHeader: {
    padding: '7px 8px 8px',
    borderBottom: '1px solid hsl(var(--border))',
    marginBottom: 4,
  },
  contextName: {
    font: '760 12px -apple-system, system-ui, sans-serif',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  contextMeta: {
    color: 'hsl(var(--muted-foreground))',
    font: '650 11px -apple-system, system-ui, sans-serif',
    marginTop: 2,
  },
  contextItem: {
    width: '100%',
    minHeight: 30,
    border: 0,
    borderRadius: 6,
    background: 'transparent',
    color: 'hsl(var(--foreground))',
    textAlign: 'start',
    font: '700 12px -apple-system, system-ui, sans-serif',
    padding: '0 8px',
    cursor: 'pointer',
  },
  contextDivider: {
    height: 1,
    background: 'hsl(var(--border) / 0.8)',
    margin: '4px 2px',
  },
  presentationBadge: {
    position: 'absolute',
    top: 18,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 28,
    padding: '7px 14px',
    borderRadius: 999,
    background: 'rgba(20, 20, 20, 0.72)',
    color: '#f4f5f7',
    font: '650 12px -apple-system, system-ui, sans-serif',
    letterSpacing: 0.2,
    backdropFilter: 'blur(12px)',
    boxShadow: '0 10px 28px rgb(0 0 0 / 0.32)',
  },
  emptyCta: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    pointerEvents: 'auto',
    color: 'hsl(var(--foreground))',
    textAlign: 'center',
  },
  emptyCtaTitle: {
    font: '800 18px -apple-system, system-ui, sans-serif',
    color: 'hsl(var(--foreground))',
  },
  emptyCtaMessage: {
    maxWidth: 420,
    color: 'hsl(var(--muted-foreground))',
    font: '600 13px -apple-system, system-ui, sans-serif',
    lineHeight: 1.4,
  },
  emptyCtaButton: {
    marginTop: 6,
    height: 36,
    padding: '0 16px',
    borderRadius: 8,
    border: '1px solid hsl(var(--primary) / 0.4)',
    background: 'hsl(var(--primary) / 0.12)',
    color: 'hsl(var(--foreground))',
    font: '750 13px -apple-system, system-ui, sans-serif',
    cursor: 'pointer',
  },
  contextSubmenu: {
    display: 'flex',
    flexDirection: 'column',
    paddingInlineStart: 12,
    borderInlineStart: '2px solid hsl(var(--border))',
    marginInlineStart: 4,
    marginBlock: 2,
    maxHeight: 320,
    overflowY: 'auto',
  },
};

export function dockToggleStyle(active, mobile = false) {
  return {
    ...styles.dockButton,
    ...(mobile ? styles.dockButtonMobile : null),
    background: active ? 'hsl(var(--primary) / 0.14)' : 'hsl(var(--secondary))',
    borderColor: active ? 'hsl(var(--primary) / 0.45)' : 'hsl(var(--border))',
    color: active ? 'hsl(var(--foreground))' : 'hsl(var(--muted-foreground))',
  };
}
