import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const OUT = process.env.OUT, OPTS = process.env.OPTS;
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 760 }, deviceScaleFactor: 2 });
const errs = []; p.on('pageerror', (e) => errs.push('PAGEERR: ' + e.message));
await p.addInitScript((opts) => { localStorage.setItem('cloudtreeweb-has-imported', '1'); if (opts) localStorage.setItem('cloudtreeweb:interactive-tree-viewer-options', opts); }, OPTS);
const data = await readFile(resolve(process.cwd(), 'public/family-data.json'), 'utf8');
await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await p.evaluate(async (j) => { const m = await import('/src/lib/data/index.js'); await m.getAppDataClient().records.importDataset(JSON.parse(j)); }, data);
await p.goto('http://localhost:3000/tree', { waitUntil: 'networkidle' });
await p.waitForFunction(() => !/Loading tree/.test(document.body.innerText || ''), { timeout: 30000 }).catch(() => {});
await p.waitForTimeout(Number(process.env.SETTLE || 6500));
await p.evaluate(() => { document.querySelectorAll('header, nav, aside, [class*=toolbar], [class*=panel]').forEach((e) => { e.style.opacity = '0.05'; }); });
await p.screenshot({ path: OUT });
console.log('saved', OUT, 'errors:', JSON.stringify(errs.slice(0,5)));
await b.close();
